- hosts: all
  become: yes
  tasks:  
  - name: Download file directly from GitHub
    ansible.builtin.get_url:
     url: "http://github.com/rajeshkumarredhat/devops/kkk.txt"
     dest: "/tmp/repo.txt"
     mode: '0644'
