- hosts: all
  become: yes
  tasks:  
  - name: Download file directly from GitHub
    ansible.builtin.get_url:
     url: "https://github.com/rajeshkumarredhat/devops/blob/master/kkk.txt:"
     dest: "/tmp/repo.txt"
     mode: '0644'
